name: "CCIS1505 Semester"  # CHANGE ME
baseurl: /semester # CHANGE ME
github_org_url: https://github.com/htc-ccis1505-semester # CHANGE ME
github_org_name: "HTC CCIS1505 Semester" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

morea_course: CCIS 1505
morea_domain: http://htc-ccis1515.github.io/
morea_google_analytics_tracking_id: "UA-63189236-3"
googleCalendarApiKey: AIzaSyDEUR96Sv3mP4FGEBjaMqX0t0ftyRKUges	 
googleCalendarId: 'q6hg5nt557scbdjtbscikg2lmc@group.calendar.google.com'
